JS_kadai2
KangoKishino/kadai pull request #5
Opened 2020-11-10 05:02 UTC by KangoKishino

JS課題2提出します。

2020-11-10 13:16 UTC, myzktkyk requested changes
動作は問題ありませんでした。
コードの記述について、1点確認事項がありコメントをしています 🙏

2020-11-10 13:16 UTC, myzktkyk commented on js_kadai/js_kadai2/js/main.js
> +const $run = document.getElementById('run');
変数名に `$` がついていますが、何か意味があったりしますか？
jQuery を使う場合は慣習として変数に `$` を付けますが、そうでない場合は使わない方が一般的かと思い、確認してます。

2020-11-10 13:27 UTC, KangoKishino commented on js_kadai/js_kadai2/js/main.js
> +const $run = document.getElementById('run');
レビューありがとうございます。
$はjQueryだけの慣習なのですね、勘違いしていました。

2020-11-12 00:13 UTC, niganium commented
確認しました。問題ありません！！

2020-11-12 00:17 UTC, merged